### ISSUE TITLE
custom externals needs dependencies - but shouldn't

### ISSUE THREAD

**Issue by jassigill2000** [irods/irods_rule_engine_plugin_update_collection_mtime#19]
- [x] master
- [x] 4-2-stable
---
irods-dev and irods-runtime need fmt and nanodbc to be installed

this is a leaky abstraction around local/passed externals

we'll merge for release, but this needs to be removed again later.

**Comment by korydraughn** [comment]
Isn't this needed on master too?

**Comment by trel** [comment]
seems so, please cherry-pick
