### ISSUE TITLE
Build fails becuase "json.hpp" not found

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_rule_engine_plugin_update_collection_mtime#21]
`#include "json.hpp"` was added to `lib/filesystem/include/filesystem/filesystem.hpp`.
`lib/filesystem/include/filesystem/filesystem.hpp` is in the include hierarchy, but the include directory for jsoncpp is never added to the include directories list
```
In file included from /re_update_collection_mtime_source/src/libirods_rule_engine_plugin-update_collection_mtime.cpp:5:
In file included from /usr/include/irods/irods_get_l1desc.hpp:5:
In file included from /usr/include/irods/filesystem.hpp:4:
/usr/include/irods/filesystem/filesystem.hpp:17:10: fatal error: 'json.hpp' file not found
#include "json.hpp"
         ^~~~~~~~~~
```

The easy solution is to just add `${IRODS_EXTERNALS_FULLPATH_JSON}/include` to the list of include directories in `CMakeLists.txt` in this repository.

HOWEVER, since `#include "json.hpp"` is in the **public** headers, the `irods-dev` cmake targets file needs to pass it down.
From the [CMake documentation on `INTERFACE_INCLUDE_DIRECTORIES`](https://cmake.org/cmake/help/v3.11/prop_tgt/INTERFACE_INCLUDE_DIRECTORIES.html):
> Targets may populate this property to publish the include directories required to compile against the headers for the target. The [`target_include_directories()`](https://cmake.org/cmake/help/v3.11/command/target_include_directories.html) command populates this property with values given to the `PUBLIC` and `INTERFACE` keywords. Projects may also get and set the property directly.
>
> When target dependencies are specified using [`target_include_directories()`](https://cmake.org/cmake/help/v3.11/command/target_include_directories.html), CMake will read this property from all target dependencies to determine the build properties of the consumer.

**Comment by trel** [comment]
This plugin functionality has been consumed by the irods server for 4.2.9 -- https://github.com/irods/irods/issues/5063

It does not need to be updated here.   Closing.
